FROM node:20-alpine
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# We don't copy the whole code here because we will mount it as a volume 
# in docker-compose for hot-reloading.

CMD ["npm", "run", "dev"]